CHANGELOG.rst, pydocx/DocxParser.py, pydocx/__init__.py, pydocx/openxml.py, pydocx/packaging.py, pydocx/parsers/Docx2Html.py, pydocx/tests/__init__.py, pydocx/tests/test_html.py, pydocx/util/zip.py, pydocx/wordml.py
Reference: ECMA 376 17.11
A basic initial implementation for footnotes.
* This doesn't process `endnotes.xml`
* `numFmt` is ignored and always uses decimals
* Footnotes are always placed at the very end of the document, regardless of `pos`. HTML has no concept of pages, but it could handle the beneath text option.
* `numRestart` and `numStart` are ignored, so the footnotes always start at 1, and never restarts
=> Process footnotes.xml

CHANGELOG.rst, pydocx/__init__.py, pydocx/parsers/Docx2Html.py, pydocx/tests/__init__.py, pydocx/tests/test_html.py
The HTML rendered using `pydocx --html test.docx output.html` doesn't specify `utf-8` charset even though we output `utf-8`, so we end up with results like the following:
That should instead look like:
=> Rendered HTML must include utf-8 charset header

pydocx/DocxParser.py, pydocx/__init__.py, pydocx/parsers/Docx2Html.py
Purpose
=======
Remove possible logging redundancy, increase flexibility in parsing as html
Changes
=======
* Remove `logging.basicConfig()`
- This was causing duplicate werkzeug logs in the OSF
* Add property `parsed_content`
- Having more than one `<header>` or `<footer>` tag per page isn't allowed, breaks page
Side Effects
==========
`logger.log()`'s will have to be added for continued logging.
=> Update PyDocX for greater usability as 3rd-party library

docs/conformance.rst, docs/index.rst, docs/usage.rst
I was thinking of using a table. Each row would correspond to a particular section in the specification (denoted by the section identifier, such as `17.9.1`), followed by a blurb for the section, and then to what degree PyDocX provides support for it. Would be cool if each row could link to some external resource.
Also, it may be useful for top-level sections to display a percentage of support? So `17.9` would display the percentage support of it's sub-level sections.
=> Update documentation to indicate what portions of the ECMA numbering spec are actually supported

CHANGELOG.rst, pydocx/models.py, pydocx/openxml/packaging/style_definitions_part.py, pydocx/openxml/wordprocessing/abstract_num.py, pydocx/openxml/wordprocessing/level.py, pydocx/openxml/wordprocessing/level_override.py, pydocx/openxml/wordprocessing/numbering.py, pydocx/openxml/wordprocessing/numbering_instance.py, pydocx/openxml/wordprocessing/paragraph_properties.py, pydocx/openxml/wordprocessing/run_properties.py, pydocx/openxml/wordprocessing/style.py, pydocx/openxml/wordprocessing/styles.py, tests/openxml/wordprocessing/test_run_properties.py, tests/test_models.py, tox.ini
Currently, the tag handled by a child is dictated by the parent. This is backwards. The child should be aware of the tag that it handles.
=> XML models should specify their own tag names, not parents

CHANGELOG.rst, docs/usage.rst, pydocx/__init__.py, pydocx/__main__.py
Currently you have to do `from pydocx.pydocx import PyDocX` which is somewhat redundant. Make it simpler: `from pydocx import PyDocX`
=> Make importing PyDocX easier

CHANGELOG.rst, pydocx/constants.py, pydocx/export/base.py, pydocx/export/html.py, pydocx/test/testcases.py, pydocx/test/utils.py, pydocx/util/preprocessor.py
The header processing is very HTML-centric, but it lives in the base pre-processor. Decouple this logic from the pre-processor, and split it appropriately between the base exporter and html exporter.
=> Decouple header processing from the pre-processor

CHANGELOG.rst, docs/export_mixins.rst, docs/extending.rst, docs/index.rst, pydocx/constants.py, pydocx/export/base.py, pydocx/export/html.py, pydocx/export/mixins/__init__.py, pydocx/export/mixins/convert_root_upper_roman_list_to_heading.py, pydocx/export/mixins/faked_superscript_and_subscript.py, pydocx/openxml/packaging/main_document_part.py, pydocx/openxml/packaging/numbering_definitions_part.py, pydocx/openxml/wordprocessing/__init__.py, pydocx/openxml/wordprocessing/abstract_num.py, pydocx/openxml/wordprocessing/numbering.py, pydocx/openxml/wordprocessing/numbering_properties.py, pydocx/openxml/wordprocessing/paragraph_properties.py, pydocx/test/testcases.py, pydocx/util/preprocessor.py, tests/export/mixins/test_convert_root_upper_roman_list_to_heading.py, tests/export/test_docx.py, tests/export/test_xml.py, tests/openxml/packaging/test_word_processing_document.py, tests/openxml/wordprocessing/test_abstract_num.py, tests/openxml/wordprocessing/test_numbering.py, tests/openxml/wordprocessing/test_numbering_properties.py, tests/openxml/wordprocessing/test_paragraph_properties.py
The base PyDocX exporter accepts an option `convert_root_level_upper_roman` which, if `True`, will convert root level lists that are formatted to "upperRoman" to a heading of level 2. 
* Decouple this logic from the pre-processor / exporter, and implement it in an optional mixin
* Remote the `convert_root_level_upper_roman` option
Depends on #135
=> Convert the 'Root level upper roman list to header' handling to an optional mixin

CHANGELOG.rst, pydocx/export/base.py, pydocx/openxml/packaging/style_definitions_part.py, pydocx/util/preprocessor.py
Currently, the preprocessor tracks table membership. This isn't necessary anymore.
=> Implement table-parent detection directly in parsing

pydocx/export/base.py, pydocx/models.py
```
pydocx/pydocx/models.py:248: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
if element:
pydocx/pydocx/export/base.py:318: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
if not main_document_part.footnotes_part.root_element:
```
=> Fix FutureWarning with testing element existence

pydocx/packaging.py, pydocx/test/utils.py, pydocx/util/zip.py
In several locations, we try to import from `cString` (instead of `cStringIO`). This exception is ignored because it's inside a try...except for the purpose of supporting python2/python3.
=> "cString" import doesn't exist: it's a typo

pydocx/models.py, tests/export/test_xml.py, tests/test_models.py
For example,
```
<foo>
<data>bar</data>
</foo>
```
The XML model schema should have a way of accessing "bar" in the `data` node. Currently it doesn't. We'll need this for `t` and `delText` among others.
=> Add support for modeling XML content

CHANGELOG.rst, pydocx/export/numbering_span.py, pydocx/openxml/wordprocessing/level.py, tests/export/html/test_numbering.py, tests/openxml/wordprocessing/test_level.py
It's possible for `numFmt` to be `none`. In this case, don't display any list styling.
=> Handle numFmt = none

CHANGELOG.rst, pydocx/openxml/wordprocessing/run_properties.py, tests/openxml/wordprocessing/test_run_properties.py
```
File "/home/policystat/env/lib/python2.6/site-packages/pydocx/export/base.py", line 101, in export_node
for result in caller(node):
File "/opt/pstat/versions/current/pstat/core/import_translation/translation.py", line 236, in export_run
results = super(PstatDocx2Html, self).export_run(run)
File "/home/policystat/env/lib/python2.6/site-packages/pydocx/export/base.py", line 209, in export_run
results = self.export_run_apply_properties(run, results)
File "/home/policystat/env/lib/python2.6/site-packages/pydocx/export/base.py", line 234, in export_run_apply_properties
for func in styles_to_apply:
File "/home/policystat/env/lib/python2.6/site-packages/pydocx/export/mixins/faked_superscript_and_subscript.py", line 40, in get_run_styles_to_apply
if could_be_a_faked_sub_or_superscript():
File …
```
=> Font size can be a float

CHANGELOG.rst, pydocx/export/html.py, pydocx/models.py, pydocx/openxml/wordprocessing/paragraph.py, pydocx/openxml/wordprocessing/run.py, tests/export/html/test_heading.py
Currently, headings strip out all styling information. This prevents weird cases like `<h2><strong>Foo</strong></h2>` but it also means that headings don't have any other styles, like italics. Update headings to preserve italic. Also, headings that use vanish or hidden styles should have the vanished or hidden spans applied.
=> Headings should preserve certain styles

CHANGELOG.rst, docs/development.rst, pydocx/export/html.py, tests/export/html/test_paragraph.py
Actual result: `<p>FooBar</p>`
```python
def test_single_styled_whitespace_in_text_run_is_preserved(self):
document_xml = '''
<p>
<r>
<t>Foo</t>
</r>
<r>
<rPr>
<b />
</rPr>
<t> </t>
</r>
<r>
<t>Bar</t>
</r>
</p>
'''
document = WordprocessingDocumentFactory()
document.add(MainDocumentPart, document_xml)
expected_html = '<p>Foo Bar</p>'
self.assert_document_generates_html(document, expected_html)
```
=> Styled whitespace is ignored

CHANGELOG.rst, pydocx/__init__.py
The last change had a significant API change, so bump the minor version.
=> Increment version to 0.9.0

pydocx/export/base.py, tests/export/html/test_field_code.py, tests/export/html/test_simple_field.py
For example, the current output is:
```html
<h2><strong>Foo</strong></h2>
```
The desired output is
```html
<h2>Foo</h2>
```
This still works for non-complex field runs but is currently broken for complex field runs.
=> Heading inside complex field has strong applied

pydocx/openxml/wordprocessing/hyperlink.py, tests/export/html/test_hyperlink.py
Some representations of Hyperlinks separate the link from the anchor. The resulting href values in the HTML don't include the anchor part.
This pull-request fixes that. More details in issue #205.
Closes #205
=> Include the anchor in a hyperlink target_uri if it exists

AUTHORS, CHANGELOG.rst, pydocx/__init__.py, pydocx/__main__.py, setup.py, tests/test_main.py
- Adds a new entry-point function for the command line tool `pydocx` in order to avoid ambiguity between invocation through CLI and invocation during tests
- Implement new tests for the CLI tool
=> Fix #197: Conversion using CLI

CHANGELOG.rst, pydocx/__init__.py, pydocx/export/base.py, pydocx/openxml/vml/__init__.py, pydocx/openxml/vml/rect.py, tests/export/html/test_rect.py
```
<mc:AlternateContent>
<mc:Fallback>
<w:pict>
<v:rect fillcolor="#FFFFFF" strokecolor="#000000" strokeweight="1pt" style="position:absolute;rotation:0">
<v:textbox>
<w:txbxContent>
<w:p>
<w:r>
<w:t>AAA</w:t>
</w:r>
</w:p>
<w:txbxContent>
<v:textbox>
<v:rect>
<w:pict>
<mc:Fallback>
</mc:AlternateContent>
```
=> Picts can have rects, which can have textbox

CHANGELOG.rst, pydocx/__init__.py, pydocx/openxml/vml/rect.py, pydocx/openxml/vml/shape.py, pydocx/test/document_builder.py, tests/export/test_xml.py, tests/templates/rect.xml
```
File "/home/policystat/env/lib/python2.7/site-packages/pydocx/export/base.py", line 218, in export_node
for result in results:
File "/home/policystat/env/lib/python2.7/site-packages/pydocx/export/html.py", line 127, in apply
for result in results:
File "/home/policystat/env/lib/python2.7/site-packages/pydocx/export/base.py", line 252, in yield_nested
for result in func(item):
File "/home/policystat/env/lib/python2.7/site-packages/pydocx/export/base.py", line 218, in export_node
for result in results:
File "/home/policystat/env/lib/python2.7/site-packages/pydocx/export/html.py", line 591, in export_table_cell
for result in results:
File "/home/policystat/env/lib/python2.7/site-packages/pydocx/export/html.py", line 127, in apply
for result in results:
File …
```
=> Rect tag needs `get_style` method.

docs/index.rst, docs/plugins.rst
This is a quick pass at some documentation for the third party plugins I wrote. I tried using the language that the rest of the documentation uses, but I may have injected a bit more personality than intended. Very open to rewrites; Just wanted to get something going.
Per #195  /cc @winhamwr 
The resulting documentation page looks like this:
=> Add a plugins section to the documentation

CHANGELOG.rst, pydocx/openxml/wordprocessing/paragraph_properties.py, tests/openxml/wordprocessing/test_paragraph_properties.py
Some .docx files that we're seeing in the wild are using a non-integer value for the `indentation_hanging` attribute. It looks something like: `<ind hanging="504.00000000000006">`
This causes a crash when we try to [cast to int](https://github.com/CenterForOpenScience/pydocx/blob/master/pydocx/openxml/wordprocessing/paragraph_properties.py#L40).
I'm not sure if these documents are violating the spec, but we've seen 123 cases of this in the last 8 days.
```python
Traceback (most recent call last):
File "/home/policystat/env/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
R = retval = fun(*args, **kwargs)
File "/home/policystat/env/lib/python2.7/site-packages/newrelic-2.58.1.44/newrelic/hooks/application_celery.py", line 66, in wrapper
return wrapped(*args, …
```
=> `ValueError: invalid literal for int() with base 10:` crash calling `start_margin_position`

pydocx/export/html.py, pydocx/openxml/wordprocessing/__init__.py, pydocx/openxml/wordprocessing/bookmark.py, pydocx/openxml/wordprocessing/paragraph.py, tests/export/html/test_heading.py, tests/export/html/test_hyperlink.py
I tried fixing #221 and this is the rough solution I have for now. If this looks ok, I can polish it up and add tests.
=> Don't drop internal links
